from tool.tool import *

data_path = 'C:/Users/cui/Desktop/python/credit/data/'

with timer('reading data...'):
    test = pd.read_csv(data_path + 'application_test.csv').replace(365243,np.nan)
    train = pd.read_csv(data_path + 'application_train.csv').replace(365243,np.nan)
    bureau = pd.read_csv(data_path + 'bureau.csv').replace(365243,np.nan)
    bureau_balance = pd.read_csv(data_path + 'bureau_balance.csv').replace(365243,np.nan)
    ccb = pd.read_csv(data_path + 'credit_card_balance.csv').replace(365243,np.nan)
    #HomeCredit_columns_description = pd.read_csv(data_path + 'HomeCredit_columns_description.csv')
    ins = pd.read_csv(data_path + 'installments_payments.csv').replace(365243,np.nan)
    POS_CASH_balance = pd.read_csv(data_path + 'POS_CASH_balance.csv').replace(365243,np.nan)
    prev = pd.read_csv(data_path + 'previous_application.csv').replace(365243,np.nan)
    sample_submission = pd.read_csv(data_path + 'sample_submission.csv')

test.to_csv(data_path + 'application_test.csv', index=False)
train.to_csv(data_path + 'application_train.csv', index=False)
bureau.to_csv(data_path + 'bureau.csv', index=False)
bureau_balance.to_csv(data_path + 'bureau_balance.csv', index=False)
ccb.to_csv(data_path + 'credit_card_balance.csv', index=False)
#HomeCredit_columns_description.to_csv(data_path + 'HomeCredit_columns_description.csv', index=False)
ins.to_csv(data_path + 'installments_payments.csv', index=False)
POS_CASH_balance.to_csv(data_path + 'POS_CASH_balance.csv', index=False)
prev.to_csv(data_path + 'previous_application.csv', index=False)
sample_submission.to_csv(data_path + 'sample_submission.csv', index=False)

test.to_feather(data_path + 'application_test.feather')
train.to_feather(data_path + 'application_train.feather')
bureau.to_feather(data_path + 'bureau.feather')
bureau_balance.to_feather(data_path + 'bureau_balance.feather')
ccb.to_feather(data_path + 'credit_card_balance.feather')
#HomeCredit_columns_description.to_feather(data_path + 'HomeCredit_columns_description.feather')
ins.to_feather(data_path + 'installments_payments.feather')
POS_CASH_balance.to_feather(data_path + 'POS_CASH_balance.feather')
prev.to_feather(data_path + 'previous_application.feather')
sample_submission.to_feather(data_path + 'sample_submission.feather')

test = pd.read_feather(data_path + 'application_test.feather')
train = pd.read_feather(data_path + 'application_train.feather')
bureau = pd.read_feather(data_path + 'bureau.feather')
bureau_balance = pd.read_feather(data_path + 'bureau_balance.feather')
credit_card_balance = pd.read_feather(data_path + 'credit_card_balance.feather')
#HomeCredit_columns_description = pd.read_feather(data_path + 'HomeCredit_columns_description.feather')
ins = pd.read_feather(data_path + 'installments_payments.feather')
POS_CASH_balance = pd.read_feather(data_path + 'POS_CASH_balance.feather')
previous_application = pd.read_feather(data_path + 'previous_application.feather')
sample_submission = pd.read_feather(data_path + 'sample_submission.feather')

print(test.shape)
print(train.shape)
print(bureau.shape)
print(bureau_balance.shape)
print(credit_card_balance.shape)
print(installments_payments.shape)
print(POS_CASH_balance.shape)
print(previous_application.shape)
print(sample_submission.shape)


print('label的正负比例：  {}'.format(train['TARGET'].mean()))
print('性别转化率： {}'.format(analyse(train,'CODE_GENDER','TARGET')))
print('是否有房转化率： {}'.format(analyse(train,'FLAG_OWN_REALTY','TARGET')))
print('是否有车转化率： {}'.format(analyse(train,'FLAG_OWN_CAR','TARGET')))
print('子女数转化率： {}'.format(analyse(train,'CNT_CHILDREN','TARGET')))
print('收入转化率： {}'.format(analyse2(train,'AMT_INCOME_TOTAL','TARGET',5)))